# This file was created automatically by PyQt5 Designer which provides
# a template for the Real-Time prediction application.
# All the other files in this folder were created by me (1800836).

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1620, 875)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1620, 875))
        MainWindow.setMaximumSize(QtCore.QSize(1620, 875))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowTitle("")
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(560, 0, 528, 874))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.GoogLeNet_dense = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoogLeNet_dense.sizePolicy().hasHeightForWidth())
        self.GoogLeNet_dense.setSizePolicy(sizePolicy)
        self.GoogLeNet_dense.setMinimumSize(QtCore.QSize(260, 180))
        self.GoogLeNet_dense.setMaximumSize(QtCore.QSize(260, 180))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.GoogLeNet_dense.setFont(font)
        self.GoogLeNet_dense.setAlignment(QtCore.Qt.AlignCenter)
        self.GoogLeNet_dense.setObjectName("GoogLeNet_dense")
        self.gridLayout.addWidget(self.GoogLeNet_dense, 10, 2, 1, 1)
        self.VGG_dense = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VGG_dense.sizePolicy().hasHeightForWidth())
        self.VGG_dense.setSizePolicy(sizePolicy)
        self.VGG_dense.setMinimumSize(QtCore.QSize(260, 180))
        self.VGG_dense.setMaximumSize(QtCore.QSize(260, 180))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VGG_dense.setFont(font)
        self.VGG_dense.setAlignment(QtCore.Qt.AlignCenter)
        self.VGG_dense.setObjectName("VGG_dense")
        self.gridLayout.addWidget(self.VGG_dense, 10, 0, 1, 1)
        self.AlexNet_check = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.AlexNet_check.setMinimumSize(QtCore.QSize(0, 15))
        self.AlexNet_check.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        font.setKerning(True)
        self.AlexNet_check.setFont(font)
        self.AlexNet_check.setObjectName("AlexNet_check")
        self.gridLayout.addWidget(self.AlexNet_check, 4, 0, 1, 1)
        self.VGG_check = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.VGG_check.setMinimumSize(QtCore.QSize(0, 15))
        self.VGG_check.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.VGG_check.setFont(font)
        self.VGG_check.setObjectName("VGG_check")
        self.gridLayout.addWidget(self.VGG_check, 6, 2, 1, 1)
        self.GoogLeNet_img = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoogLeNet_img.sizePolicy().hasHeightForWidth())
        self.GoogLeNet_img.setSizePolicy(sizePolicy)
        self.GoogLeNet_img.setMinimumSize(QtCore.QSize(260, 195))
        self.GoogLeNet_img.setMaximumSize(QtCore.QSize(260, 195))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.GoogLeNet_img.setFont(font)
        self.GoogLeNet_img.setAlignment(QtCore.Qt.AlignCenter)
        self.GoogLeNet_img.setObjectName("GoogLeNet_img")
        self.gridLayout.addWidget(self.GoogLeNet_img, 3, 2, 1, 1)
        self.ResNet_check = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ResNet_check.setMinimumSize(QtCore.QSize(0, 15))
        self.ResNet_check.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.ResNet_check.setFont(font)
        self.ResNet_check.setObjectName("ResNet_check")
        self.gridLayout.addWidget(self.ResNet_check, 9, 0, 1, 1)
        self.VGG_img = QtWidgets.QLabel(self.gridLayoutWidget)
        self.VGG_img.setMinimumSize(QtCore.QSize(260, 195))
        self.VGG_img.setMaximumSize(QtCore.QSize(260, 195))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VGG_img.setFont(font)
        self.VGG_img.setAlignment(QtCore.Qt.AlignCenter)
        self.VGG_img.setObjectName("VGG_img")
        self.gridLayout.addWidget(self.VGG_img, 5, 2, 1, 1)
        self.GoogLeNet_check = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.GoogLeNet_check.setMinimumSize(QtCore.QSize(0, 15))
        self.GoogLeNet_check.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.GoogLeNet_check.setFont(font)
        self.GoogLeNet_check.setCheckable(True)
        self.GoogLeNet_check.setTristate(False)
        self.GoogLeNet_check.setObjectName("GoogLeNet_check")
        self.gridLayout.addWidget(self.GoogLeNet_check, 4, 2, 1, 1)
        self.MNaSNet_check = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.MNaSNet_check.setMinimumSize(QtCore.QSize(0, 15))
        self.MNaSNet_check.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.MNaSNet_check.setFont(font)
        self.MNaSNet_check.setObjectName("MNaSNet_check")
        self.gridLayout.addWidget(self.MNaSNet_check, 6, 0, 1, 1)
        self.MNaSNet_img = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MNaSNet_img.sizePolicy().hasHeightForWidth())
        self.MNaSNet_img.setSizePolicy(sizePolicy)
        self.MNaSNet_img.setMinimumSize(QtCore.QSize(260, 195))
        self.MNaSNet_img.setMaximumSize(QtCore.QSize(260, 195))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.MNaSNet_img.setFont(font)
        self.MNaSNet_img.setAlignment(QtCore.Qt.AlignCenter)
        self.MNaSNet_img.setObjectName("MNaSNet_img")
        self.gridLayout.addWidget(self.MNaSNet_img, 5, 0, 1, 1)
        self.ResNet_img = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ResNet_img.setMinimumSize(QtCore.QSize(260, 195))
        self.ResNet_img.setMaximumSize(QtCore.QSize(260, 195))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ResNet_img.setFont(font)
        self.ResNet_img.setAlignment(QtCore.Qt.AlignCenter)
        self.ResNet_img.setObjectName("ResNet_img")
        self.gridLayout.addWidget(self.ResNet_img, 8, 0, 1, 1)
        self.ZFNet_check = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.ZFNet_check.setMinimumSize(QtCore.QSize(0, 15))
        self.ZFNet_check.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(9)
        self.ZFNet_check.setFont(font)
        self.ZFNet_check.setObjectName("ZFNet_check")
        self.gridLayout.addWidget(self.ZFNet_check, 9, 2, 1, 1)
        self.AlexNet_img = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AlexNet_img.setMinimumSize(QtCore.QSize(260, 195))
        self.AlexNet_img.setMaximumSize(QtCore.QSize(260, 195))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(15)
        self.AlexNet_img.setFont(font)
        self.AlexNet_img.setAlignment(QtCore.Qt.AlignCenter)
        self.AlexNet_img.setObjectName("AlexNet_img")
        self.gridLayout.addWidget(self.AlexNet_img, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(250, 0))
        self.label_6.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 11, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(250, 20))
        self.label_5.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 11, 0, 1, 1)
        self.ZFNet_img = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ZFNet_img.setMinimumSize(QtCore.QSize(260, 195))
        self.ZFNet_img.setMaximumSize(QtCore.QSize(260, 195))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ZFNet_img.setFont(font)
        self.ZFNet_img.setAlignment(QtCore.Qt.AlignCenter)
        self.ZFNet_img.setObjectName("ZFNet_img")
        self.gridLayout.addWidget(self.ZFNet_img, 8, 2, 1, 1)
        self.groupBox_dataset = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_dataset.setGeometry(QtCore.QRect(10, 0, 531, 871))
        self.groupBox_dataset.setObjectName("groupBox_dataset")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_dataset)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 531, 841))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_image = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_image.sizePolicy().hasHeightForWidth())
        self.main_image.setSizePolicy(sizePolicy)
        self.main_image.setMinimumSize(QtCore.QSize(500, 350))
        self.main_image.setMaximumSize(QtCore.QSize(500, 350))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(15)
        self.main_image.setFont(font)
        self.main_image.setFrameShape(QtWidgets.QFrame.Box)
        self.main_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_image.setTextFormat(QtCore.Qt.PlainText)
        self.main_image.setAlignment(QtCore.Qt.AlignCenter)
        self.main_image.setObjectName("main_image")
        self.verticalLayout.addWidget(self.main_image)
        self.toolBox = QtWidgets.QToolBox(self.verticalLayoutWidget)
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolBox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.toolBox.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBox.setObjectName("toolBox")
        self.dog_page = QtWidgets.QWidget()
        self.dog_page.setGeometry(QtCore.QRect(0, 0, 529, 348))
        self.dog_page.setObjectName("dog_page")
        self.dog_list = QtWidgets.QListWidget(self.dog_page)
        self.dog_list.setGeometry(QtCore.QRect(0, 0, 520, 350))
        self.dog_list.setViewMode(QtWidgets.QListView.IconMode)
        self.dog_list.setObjectName("dog_list")
        self.toolBox.addItem(self.dog_page, "")
        self.berry_page = QtWidgets.QWidget()
        self.berry_page.setGeometry(QtCore.QRect(0, 0, 529, 348))
        self.berry_page.setObjectName("berry_page")
        self.berry_list = QtWidgets.QListWidget(self.berry_page)
        self.berry_list.setGeometry(QtCore.QRect(0, 0, 520, 350))
        self.berry_list.setViewMode(QtWidgets.QListView.IconMode)
        self.berry_list.setObjectName("berry_list")
        self.toolBox.addItem(self.berry_page, "")
        self.bird_page = QtWidgets.QWidget()
        self.bird_page.setGeometry(QtCore.QRect(0, 0, 529, 348))
        self.bird_page.setObjectName("bird_page")
        self.bird_list = QtWidgets.QListWidget(self.bird_page)
        self.bird_list.setGeometry(QtCore.QRect(0, 0, 520, 350))
        self.bird_list.setViewMode(QtWidgets.QListView.IconMode)
        self.bird_list.setObjectName("bird_list")
        self.toolBox.addItem(self.bird_page, "")
        self.flower_page = QtWidgets.QWidget()
        self.flower_page.setGeometry(QtCore.QRect(0, 0, 529, 348))
        self.flower_page.setObjectName("flower_page")
        self.flower_list = QtWidgets.QListWidget(self.flower_page)
        self.flower_list.setGeometry(QtCore.QRect(0, 0, 520, 350))
        self.flower_list.setViewMode(QtWidgets.QListView.IconMode)
        self.flower_list.setObjectName("flower_list")
        self.toolBox.addItem(self.flower_page, "")
        self.other_page = QtWidgets.QWidget()
        self.other_page.setGeometry(QtCore.QRect(0, 0, 529, 348))
        self.other_page.setObjectName("other_page")
        self.other_list = QtWidgets.QListWidget(self.other_page)
        self.other_list.setGeometry(QtCore.QRect(0, 0, 520, 350))
        self.other_list.setViewMode(QtWidgets.QListView.IconMode)
        self.other_list.setObjectName("other_list")
        self.toolBox.addItem(self.other_page, "")
        self.verticalLayout.addWidget(self.toolBox)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(1100, 10, 508, 854))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.VGG_layers_first = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VGG_layers_first.sizePolicy().hasHeightForWidth())
        self.VGG_layers_first.setSizePolicy(sizePolicy)
        self.VGG_layers_first.setMinimumSize(QtCore.QSize(250, 155))
        self.VGG_layers_first.setMaximumSize(QtCore.QSize(250, 155))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VGG_layers_first.setFont(font)
        self.VGG_layers_first.setAlignment(QtCore.Qt.AlignCenter)
        self.VGG_layers_first.setObjectName("VGG_layers_first")
        self.gridLayout_2.addWidget(self.VGG_layers_first, 8, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setMinimumSize(QtCore.QSize(250, 0))
        self.label_2.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 3, 1, 1)
        self.GoogLeNet_smoothgrad = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoogLeNet_smoothgrad.sizePolicy().hasHeightForWidth())
        self.GoogLeNet_smoothgrad.setSizePolicy(sizePolicy)
        self.GoogLeNet_smoothgrad.setMinimumSize(QtCore.QSize(250, 210))
        self.GoogLeNet_smoothgrad.setMaximumSize(QtCore.QSize(250, 210))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.GoogLeNet_smoothgrad.setFont(font)
        self.GoogLeNet_smoothgrad.setAlignment(QtCore.Qt.AlignCenter)
        self.GoogLeNet_smoothgrad.setObjectName("GoogLeNet_smoothgrad")
        self.gridLayout_2.addWidget(self.GoogLeNet_smoothgrad, 5, 3, 1, 1)
        self.VGG_smoothgrad = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VGG_smoothgrad.sizePolicy().hasHeightForWidth())
        self.VGG_smoothgrad.setSizePolicy(sizePolicy)
        self.VGG_smoothgrad.setMinimumSize(QtCore.QSize(250, 210))
        self.VGG_smoothgrad.setMaximumSize(QtCore.QSize(250, 210))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VGG_smoothgrad.setFont(font)
        self.VGG_smoothgrad.setAlignment(QtCore.Qt.AlignCenter)
        self.VGG_smoothgrad.setObjectName("VGG_smoothgrad")
        self.gridLayout_2.addWidget(self.VGG_smoothgrad, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(250, 20))
        self.label_3.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 1)
        self.VGG_sal = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VGG_sal.sizePolicy().hasHeightForWidth())
        self.VGG_sal.setSizePolicy(sizePolicy)
        self.VGG_sal.setMinimumSize(QtCore.QSize(250, 210))
        self.VGG_sal.setMaximumSize(QtCore.QSize(250, 210))
        font = QtGui.QFont()
        font.setFamily("Sans")
        font.setPointSize(15)
        self.VGG_sal.setFont(font)
        self.VGG_sal.setAlignment(QtCore.Qt.AlignCenter)
        self.VGG_sal.setObjectName("VGG_sal")
        self.gridLayout_2.addWidget(self.VGG_sal, 3, 0, 1, 1)
        self.GoogLeNet_sal = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoogLeNet_sal.sizePolicy().hasHeightForWidth())
        self.GoogLeNet_sal.setSizePolicy(sizePolicy)
        self.GoogLeNet_sal.setMinimumSize(QtCore.QSize(250, 210))
        self.GoogLeNet_sal.setMaximumSize(QtCore.QSize(250, 210))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.GoogLeNet_sal.setFont(font)
        self.GoogLeNet_sal.setAlignment(QtCore.Qt.AlignCenter)
        self.GoogLeNet_sal.setObjectName("GoogLeNet_sal")
        self.gridLayout_2.addWidget(self.GoogLeNet_sal, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(250, 0))
        self.label_4.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(250, 20))
        self.label.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(250, 20))
        self.label_7.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 9, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(250, 20))
        self.label_9.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 9, 0, 1, 1)
        self.GoogLeNet_layers_last = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoogLeNet_layers_last.sizePolicy().hasHeightForWidth())
        self.GoogLeNet_layers_last.setSizePolicy(sizePolicy)
        self.GoogLeNet_layers_last.setMinimumSize(QtCore.QSize(250, 155))
        self.GoogLeNet_layers_last.setMaximumSize(QtCore.QSize(250, 155))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.GoogLeNet_layers_last.setFont(font)
        self.GoogLeNet_layers_last.setAlignment(QtCore.Qt.AlignCenter)
        self.GoogLeNet_layers_last.setObjectName("GoogLeNet_layers_last")
        self.gridLayout_2.addWidget(self.GoogLeNet_layers_last, 10, 3, 1, 1)
        self.VGG_layers_last = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VGG_layers_last.sizePolicy().hasHeightForWidth())
        self.VGG_layers_last.setSizePolicy(sizePolicy)
        self.VGG_layers_last.setMinimumSize(QtCore.QSize(250, 155))
        self.VGG_layers_last.setMaximumSize(QtCore.QSize(250, 155))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.VGG_layers_last.setFont(font)
        self.VGG_layers_last.setAlignment(QtCore.Qt.AlignCenter)
        self.VGG_layers_last.setObjectName("VGG_layers_last")
        self.gridLayout_2.addWidget(self.VGG_layers_last, 10, 0, 1, 1)
        self.GoogLeNet_layers_first = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GoogLeNet_layers_first.sizePolicy().hasHeightForWidth())
        self.GoogLeNet_layers_first.setSizePolicy(sizePolicy)
        self.GoogLeNet_layers_first.setMinimumSize(QtCore.QSize(250, 155))
        self.GoogLeNet_layers_first.setMaximumSize(QtCore.QSize(250, 155))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.GoogLeNet_layers_first.setFont(font)
        self.GoogLeNet_layers_first.setAlignment(QtCore.Qt.AlignCenter)
        self.GoogLeNet_layers_first.setObjectName("GoogLeNet_layers_first")
        self.gridLayout_2.addWidget(self.GoogLeNet_layers_first, 8, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(250, 20))
        self.label_8.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 11, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(250, 20))
        self.label_10.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 11, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        self.AlexNet_check.stateChanged['int'].connect(MainWindow.checkbox_toggled)
        self.MNaSNet_check.stateChanged['int'].connect(MainWindow.checkbox_toggled)
        self.ResNet_check.stateChanged['int'].connect(MainWindow.checkbox_toggled)
        self.ZFNet_check.stateChanged['int'].connect(MainWindow.checkbox_toggled)
        self.VGG_check.stateChanged['int'].connect(MainWindow.checkbox_toggled)
        self.GoogLeNet_check.stateChanged['int'].connect(MainWindow.checkbox_toggled)
        self.dog_list.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(MainWindow.list_index_moved)
        self.berry_list.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(MainWindow.list_index_moved)
        self.bird_list.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(MainWindow.list_index_moved)
        self.flower_list.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(MainWindow.list_index_moved)
        self.other_list.currentItemChanged['QListWidgetItem*','QListWidgetItem*'].connect(MainWindow.list_index_moved)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.GoogLeNet_dense.setText(_translate("MainWindow", "?"))
        self.VGG_dense.setText(_translate("MainWindow", "?"))
        self.AlexNet_check.setText(_translate("MainWindow", "AlexNet"))
        self.VGG_check.setText(_translate("MainWindow", "VGG"))
        self.GoogLeNet_img.setText(_translate("MainWindow", "?"))
        self.ResNet_check.setText(_translate("MainWindow", "ResNet"))
        self.VGG_img.setText(_translate("MainWindow", "?"))
        self.GoogLeNet_check.setText(_translate("MainWindow", "GoogLeNet"))
        self.MNaSNet_check.setText(_translate("MainWindow", "MNaSNet"))
        self.MNaSNet_img.setText(_translate("MainWindow", "?"))
        self.ResNet_img.setText(_translate("MainWindow", "?"))
        self.ZFNet_check.setText(_translate("MainWindow", "ZFNet"))
        self.AlexNet_img.setText(_translate("MainWindow", "?"))
        self.label_6.setText(_translate("MainWindow", "Class Dense Layer Visualisation - GoogLeNet"))
        self.label_5.setText(_translate("MainWindow", "Class Dense Layer Visualisation - VGG"))
        self.ZFNet_img.setText(_translate("MainWindow", "?"))
        self.groupBox_dataset.setTitle(_translate("MainWindow", "Dataset"))
        self.main_image.setText(_translate("MainWindow", "?"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.dog_page), _translate("MainWindow", "Dogs"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.berry_page), _translate("MainWindow", "Berries"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.bird_page), _translate("MainWindow", "Birds"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.flower_page), _translate("MainWindow", "Flowers"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.other_page), _translate("MainWindow", "Other"))
        self.VGG_layers_first.setText(_translate("MainWindow", "?"))
        self.label_2.setText(_translate("MainWindow", "  GoogLeNet  - Saliency Map"))
        self.GoogLeNet_smoothgrad.setText(_translate("MainWindow", "?"))
        self.VGG_smoothgrad.setText(_translate("MainWindow", "?"))
        self.label_3.setText(_translate("MainWindow", "VGG - SmoothGrad Saliency "))
        self.VGG_sal.setText(_translate("MainWindow", "?"))
        self.GoogLeNet_sal.setText(_translate("MainWindow", "?"))
        self.label_4.setText(_translate("MainWindow", "  GoogLeNet  - SmoothGrad Saliency "))
        self.label.setText(_translate("MainWindow", "VGG - Saliency Map"))
        self.label_7.setText(_translate("MainWindow", "GoogLeNet First Activations"))
        self.label_9.setText(_translate("MainWindow", "VGG First Activations"))
        self.GoogLeNet_layers_last.setText(_translate("MainWindow", "?"))
        self.VGG_layers_last.setText(_translate("MainWindow", "?"))
        self.GoogLeNet_layers_first.setText(_translate("MainWindow", "?"))
        self.label_8.setText(_translate("MainWindow", "VGG Last Activations"))
        self.label_10.setText(_translate("MainWindow", "GoogLeNet Last Activations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
